import { css } from '@emotion/css';
import type { GrafanaTheme2 } from '@grafana/data';

export const getStyles = (theme: GrafanaTheme2) => ({
  root: css({
    display: 'flex',
    flexDirection: 'column',
    height: '100%',
    overflow: 'hidden',
  }),
  header: css({
    padding: `${theme.spacing(1.5)} ${theme.spacing(2)}`,
    borderBottom: `1px solid ${theme.colors.border.weak}`,
    display: 'flex',
    alignItems: 'center',
    gap: theme.spacing(1.5),
    flexShrink: 0,
    background: theme.colors.background.canvas,
  }),
  backBtn: css({
    display: 'flex',
    alignItems: 'center',
    gap: theme.spacing(0.5),
    background: 'none',
    border: 'none',
    cursor: 'pointer',
    color: theme.colors.text.link,
    fontSize: theme.typography.bodySmall.fontSize,
    padding: 0,
    '&:hover': { textDecoration: 'underline' },
  }),
  traceTitle: css({
    fontWeight: theme.typography.fontWeightMedium,
    fontSize: theme.typography.body.fontSize,
    color: theme.colors.text.primary,
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  }),
  traceId: css({
    fontSize: '11px',
    fontFamily: theme.typography.fontFamilyMonospace,
    color: theme.colors.text.secondary,
  }),
  body: css({
    display: 'flex',
    flex: 1,
    minHeight: 0,
    overflow: 'hidden',
    position: 'relative',
  }),
  spanListPane: css({
    overflow: 'auto',
    overscrollBehavior: 'contain',
    flexShrink: 0,
  }),
  resizeHandle: css({
    width: '5px',
    flexShrink: 0,
    cursor: 'col-resize',
    position: 'relative',
    userSelect: 'none',
    '&::after': {
      content: '""',
      position: 'absolute',
      top: 0,
      bottom: 0,
      left: '2px',
      width: '1px',
      background: theme.colors.border.weak,
    },
    '&:hover::after': {
      background: theme.colors.primary.border,
      width: '2px',
      left: '1.5px',
    },
  }),
  detailPane: css({
    flex: 1,
    overflow: 'auto',
    overscrollBehavior: 'contain',
    background: theme.colors.background.primary,
  }),
  detailPlaceholder: css({
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    height: '100%',
    color: theme.colors.text.disabled,
    flexDirection: 'column',
    gap: theme.spacing(1),
  }),
  columnHeader: css({
    display: 'flex',
    padding: `${theme.spacing(0.75)} ${theme.spacing(1)}`,
    borderBottom: `2px solid ${theme.colors.border.medium}`,
    background: theme.colors.background.secondary,
    fontSize: '11px',
    fontWeight: theme.typography.fontWeightMedium,
    color: theme.colors.text.secondary,
    textTransform: 'uppercase',
    letterSpacing: '0.05em',
    position: 'sticky',
    top: 0,
    zIndex: 1,
  }),
  colName: css({ flex: 1 }),
  colDuration: css({ width: '70px', textAlign: 'right' }),
  colBar: css({ width: '140px', marginLeft: theme.spacing(1) }),
  spanFilterRow: css({
    display: 'flex',
    alignItems: 'center',
    padding: `${theme.spacing(0.5)} ${theme.spacing(1)}`,
    borderBottom: `1px solid ${theme.colors.border.medium}`,
    background: theme.colors.background.secondary,
    gap: theme.spacing(0.5),
  }),
  spanFilterInput: css({
    flex: 1,
    background: theme.colors.background.primary,
    border: `1px solid ${theme.colors.border.medium}`,
    borderRadius: theme.shape.radius.default,
    color: theme.colors.text.primary,
    fontSize: theme.typography.bodySmall.fontSize,
    fontFamily: theme.typography.fontFamilyMonospace,
    padding: `${theme.spacing(0.375)} ${theme.spacing(0.75)}`,
    outline: 'none',
    '&::placeholder': { color: theme.colors.text.disabled },
    '&:focus': { borderColor: theme.colors.primary.border },
  }),
  spanFilterClear: css({
    background: 'none',
    border: 'none',
    cursor: 'pointer',
    color: theme.colors.text.secondary,
    display: 'flex',
    alignItems: 'center',
    padding: '2px',
    borderRadius: '2px',
    '&:hover': { color: theme.colors.text.primary },
  }),
  spanFilterCount: css({
    fontSize: '11px',
    color: theme.colors.text.secondary,
    fontFamily: theme.typography.fontFamilyMonospace,
    whiteSpace: 'nowrap',
  }),
  spanDetailHeader: css({
    padding: `${theme.spacing(1)} ${theme.spacing(1.5)}`,
    borderBottom: `1px solid ${theme.colors.border.weak}`,
    background: theme.colors.background.secondary,
  }),
  spanDetailTitle: css({
    fontWeight: theme.typography.fontWeightMedium,
    fontSize: theme.typography.bodySmall.fontSize,
    color: theme.colors.text.primary,
    marginBottom: theme.spacing(0.25),
  }),
  spanDetailMeta: css({
    fontSize: '11px',
    color: theme.colors.text.secondary,
    display: 'flex',
    gap: theme.spacing(1.5),
    flexWrap: 'wrap',
    fontFamily: theme.typography.fontFamilyMonospace,
  }),
  spanStatusError: css({
    display: 'inline-flex',
    alignItems: 'center',
    gap: theme.spacing(0.5),
    color: theme.colors.error.text,
    fontWeight: theme.typography.fontWeightMedium,
    fontFamily: theme.typography.fontFamilyMonospace,
    fontSize: '11px',
  }),
  spanStatusMessage: css({
    fontSize: '11px',
    color: theme.colors.error.text,
    marginTop: theme.spacing(0.5),
    fontFamily: theme.typography.fontFamilyMonospace,
    wordBreak: 'break-word',
  }),
  attrSection: css({
    padding: `${theme.spacing(1)} ${theme.spacing(1.5)}`,
  }),
  attrTable: css({
    width: '100%',
    fontSize: theme.typography.bodySmall.fontSize,
    borderCollapse: 'collapse',
  }),
  attrRow: css({
    '&:hover': { background: theme.colors.action.hover },
  }),
  attrKey: css({
    padding: `${theme.spacing(0.25)} ${theme.spacing(0.75)} ${theme.spacing(0.25)} 0`,
    color: theme.colors.text.secondary,
    verticalAlign: 'top',
    whiteSpace: 'nowrap',
    fontFamily: theme.typography.fontFamilyMonospace,
    width: '45%',
  }),
  attrValue: css({
    padding: `${theme.spacing(0.25)} 0`,
    color: theme.colors.text.primary,
    fontFamily: theme.typography.fontFamilyMonospace,
    wordBreak: 'break-word',
    overflowWrap: 'anywhere',
    minWidth: 0,
  }),
  divider: css({
    borderTop: `1px solid ${theme.colors.border.weak}`,
    margin: `${theme.spacing(1)} 0`,
  }),
  sectionLabel: css({
    fontSize: '11px',
    fontWeight: theme.typography.fontWeightMedium,
    color: theme.colors.text.secondary,
    textTransform: 'uppercase',
    letterSpacing: '0.05em',
    padding: `${theme.spacing(0.75)} ${theme.spacing(1.5)}`,
    borderBottom: `1px solid ${theme.colors.border.weak}`,
    background: theme.colors.background.secondary,
  }),
  statsRow: css({
    display: 'flex',
    gap: theme.spacing(3),
    padding: `${theme.spacing(0.75)} ${theme.spacing(2)}`,
    borderBottom: `1px solid ${theme.colors.border.weak}`,
    background: theme.colors.background.canvas,
    fontSize: theme.typography.bodySmall.fontSize,
    flexShrink: 0,
  }),
  stat: css({
    display: 'flex',
    flexDirection: 'column',
    gap: '2px',
  }),
  statLabel: css({
    color: theme.colors.text.secondary,
    fontSize: '11px',
  }),
  statValue: css({
    fontWeight: theme.typography.fontWeightMedium,
    fontFamily: theme.typography.fontFamilyMonospace,
  }),
  expandHandle: css({
    width: '20px',
    flexShrink: 0,
    background: theme.colors.background.secondary,
    border: 'none',
    borderRight: `1px solid ${theme.colors.border.medium}`,
    cursor: 'pointer',
    color: theme.colors.text.secondary,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 0,
    '&:hover': {
      background: theme.colors.action.hover,
      color: theme.colors.text.primary,
    },
  }),
  shimmer: css({
    borderRadius: '3px',
    background: `linear-gradient(90deg, ${theme.colors.background.secondary} 25%, ${theme.colors.action.hover} 50%, ${theme.colors.background.secondary} 75%)`,
    backgroundSize: '200% 100%',
    animation: 'traceShimmer 1.5s infinite linear',
    '@keyframes traceShimmer': {
      '0%': { backgroundPosition: '200% 0' },
      '100%': { backgroundPosition: '-200% 0' },
    },
  }),
  traceLoader: css({
    display: 'flex',
    flex: 1,
    overflow: 'hidden',
  }),
  traceLoaderLeft: css({
    width: '500px',
    flexShrink: 0,
    borderRight: `1px solid ${theme.colors.border.medium}`,
    display: 'flex',
    flexDirection: 'column',
  }),
  traceLoaderRight: css({
    flex: 1,
    overflow: 'hidden',
    background: theme.colors.background.primary,
  }),
  traceLoaderStatsBar: css({
    display: 'flex',
    gap: theme.spacing(3),
    padding: `${theme.spacing(0.75)} ${theme.spacing(2)}`,
    borderBottom: `1px solid ${theme.colors.border.weak}`,
    background: theme.colors.background.canvas,
    flexShrink: 0,
  }),
});
